// Generated by https://quicktype.io

export interface PlacesReponse {
  type:        string;
  query:       string[];
  features:    Feature[];
  attribution: string;
}

export interface Feature {
  id:            string;
  type:          string;
  place_type:    string[];
  relevance:     number;
  properties:    Properties;
  text_en:       string;
  place_name_en: string;
  text:          string;
  place_name:    string;
  center:        number[];
  geometry:      Geometry;
  address?:      string;
  context:       Context[];
  bbox?:         number[];
  language_en?:  Language;
  language?:     Language;
}

export interface Context {
  id:           string;
  text_en:      string;
  text:         string;
  short_code?:  string;
  wikidata?:    string;
  language_en?: Language;
  language?:    Language;
}

export enum Language {
  En = "en",
}

export interface Geometry {
  type:          string;
  coordinates:   number[];
  interpolated?: boolean;
}

export interface Properties {
  accuracy?:   string;
  short_code?: string;
  wikidata?:   string;
}
